name: Sandcastles
favicon: null
layout_spectrum: 0.76115
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cecec6'
    - '#000000'
    - '#95806d'
    - '#635a53'
    - '#4c2b1c'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
