name: Sandcastles
favicon: null
layout_spectrum: 0.76115
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73884594-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6149'
    - '#030303'
    - '#2f3034'
    - '#c8c8ca'
    - '#f1f8fe'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
